spring:
  application:
    name: smartdelivery

  config:
    import: optional:file:.env[.properties]


  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

  rabbitmq:
    addresses: ${RABBITMQ_URL}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VHOST}

feign:
  client:
    config:
      viacep-service:
        url: https://viacep.com.br/ws/


