spring:
  application:
    name: smartdelivery


  datasource:
    url: jdbc:postgresql://localhost:5433/smartdelivery
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    addresses: amqps://cfrtbfpc:id3Ue5Xkoh0smE6pGrXrZgtPKWesB-CP@stingray.rmq.cloudamqp.com/cfrtbfpc
    username: cfrtbfpc
    password: id3Ue5Xkoh0smE6pGrXrZgtPKWesB-CP
    virtual-host: cfrtbfpc


